#-*- coding: utf-8 -*-

from config import *
from modules import *

pepurl2 = 'http://192.168.1.2'
pepurl = 'http://192.168.1.1'

Master_SN = '1825-0FA7-6382'


def Setting():
    
    driver = Bopen()
    UIsLogin(pepurl)
    Bvisit (pepurl + '/cgi-bin/MANGA/index.cgi?mode=config&option=advlan')
    time.sleep(2)

    SBfillT('IP Address','192.168.1.2','1','1','1')
    time.sleep(2)
    Bncheck('table.form_table:nth-child(10) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(1) > input:nth-child(1)')
    time.sleep(2)
    BclickT ('Save')
    time.sleep(5)
    UIsApply(pepurl2)
    time.sleep(5)
    Bquit()

    os.system('netsh interface set interface "EXT" admin=enable')
    os.system('netsh interface ip set address "INT" static 192.168.1.50 255.255.255.0')

    time.sleep(20)

    # HA LAN Setting
    tn = telnetlib.Telnet('10.88.1.101')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/37\r\n")
    time.sleep(2)
    tn.write("vlan participation include 146\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 137\r\n")
    time.sleep(2)
    tn.write("vlan pvid 146\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close


    # HA WAN1 Setting
    tn = telnetlib.Telnet('10.88.1.102')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/15\r\n")
    time.sleep(2)
    tn.write("vlan participation include 235\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 215\r\n")
    time.sleep(2)
    tn.write("vlan pvid 235\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close

    # HA WAN2 Setting
    tn = telnetlib.Telnet('10.88.1.102')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/16\r\n")
    time.sleep(2)
    tn.write("vlan participation include 236\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 216\r\n")
    time.sleep(2)
    tn.write("vlan pvid 236\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close

    os.system('netsh interface set interface "EXT" admin=disable')
    os.system('netsh interface ip set address "INT" source=dhcp')


    driver = Bopen()
    UIsLogin(pepurl2)
    Bvisit('http://192.168.1.2/cgi-bin/MANGA/index.cgi?mode=config&option=vrrpdemo')
    time.sleep(2)
    Bcheck('#mainContent > form > table > tbody > tr:nth-child(1) > td > table > tbody:nth-child(2) > tr > td.tablecontent2b > input')
    time.sleep(2)
    Bclick('#vrrp_panel > tr:nth-child(1) > td.tablecontent2b > select > option:nth-child(1)')
    Bclick('#vrrpPrioritySlave')
    Bcheck('#hasync_enable_yes')
    Bfill('#hasync_panel > td.tablecontent2b > input:nth-child(2)', Master_SN)
    Bfill('#vrrp_panel > tr:nth-child(6) > td.tablecontent2b > input[type="text"]','192.168.1.3')
    BclickT('Save')
    time.sleep(5)
    UIsApply(pepurl2)
    Bquit()


    driver = Bopen()
    UIsLogin(pepurl)
    Bvisit('http://192.168.1.1/cgi-bin/MANGA/index.cgi?mode=config&option=vrrpdemo')
    time.sleep(2)
    Bcheck('#mainContent > form > table > tbody > tr:nth-child(1) > td > table > tbody:nth-child(2) > tr > td.tablecontent2b > input')
    time.sleep(2)
    Bclick('#vrrp_panel > tr:nth-child(1) > td.tablecontent2b > select > option:nth-child(1)')
    Bfill('#vrrp_panel > tr:nth-child(6) > td.tablecontent2b > input[type="text"]','192.168.1.3')
    BclickT('Save')
    time.sleep(5)
    UIsApply(pepurl)
    Bquit()

    os.system('ipconfig /release')
    time.sleep(2)
    os.system('ipconfig /renew')
    time.sleep(2)

def Recover():
       
    #recover Device2
    driver = Bopen()
    UIsLogin(pepurl2)
    time.sleep(2)
    Bvisit ('http://192.168.1.2/cgi-bin/MANGA/index.cgi?mode=config&option=utconfig')
    time.sleep(2)
    Bwait('.restore_action')
    time.sleep(2)
    Bclick('.restore_action')
    time.sleep(2)
    Bwait('button.ui-button:nth-child(1)')
    time.sleep(2)
    Bclick('button.ui-button:nth-child(1)')
    time.sleep(60)
    Bquit()

    tn = telnetlib.Telnet('10.88.1.101')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/46\r\n")
    time.sleep(2)
    tn.write("shutdown\r\n")
    time.sleep(2)
    tn.close

    #recover Device1
    UIRestD()
    
    os.system('netsh interface set interface "EXT" admin=enable')
    os.system('netsh interface ip set address "INT" static 192.168.1.50 255.255.255.0')
    time.sleep(2)
    tn = telnetlib.Telnet('10.88.1.101')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/37\r\n")
    time.sleep(2)
    tn.write("vlan participation include 137\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 146\r\n")
    time.sleep(2)
    tn.write("vlan pvid 137\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close


    tn = telnetlib.Telnet('10.88.1.102')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/15\r\n")
    time.sleep(2)
    tn.write("vlan participation include 215\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 235\r\n")
    time.sleep(2)
    tn.write("vlan pvid 215\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close

    tn = telnetlib.Telnet('10.88.1.102')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/16\r\n")
    time.sleep(2)
    tn.write("vlan participation include 215\r\n")
    time.sleep(2)
    tn.write("vlan participation auto 236\r\n")
    time.sleep(2)
    tn.write("vlan pvid 216\r\n")
    time.sleep(2)
    tn.write("exit\r\n")
    time.sleep(2)
    tn.close

    tn = telnetlib.Telnet('10.88.1.101')
    time.sleep(2)
    tn.read_until("User:")
    time.sleep(2)
    tn.write("admin\r\n")
    time.sleep(2)
    tn.read_until("Password:")
    time.sleep(2)
    tn.write ('\r\n')
    time.sleep(2)
    tn.write("enable\r\n")
    time.sleep(2)        
    tn.write("config\r\n")
    time.sleep(2)
    tn.write("interface 0/46\r\n")
    time.sleep(2)
    tn.write("no shutdown\r\n")
    time.sleep(2)
    tn.close


    os.system('netsh interface set interface "EXT" admin=disable')
    os.system('netsh interface ip set address "INT" source=dhcp')


if __name__ == "__main__":

    #Setting()
    Recover()
